def programa2():
  global _hidden_verificationVariable=0
  set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
  set_tool_communication(False, 115200, 0, 1, 1.5, 3.5)
  set_tool_output_mode(0)
  set_tool_digital_output_mode(0, 1)
  set_tool_digital_output_mode(1, 1)
  set_tool_voltage(0)
  tool_wrench_limit_disable()
  set_gravity([0.0, 0.0, 9.82])
  set_safety_mode_transition_hardness(1)
  set_target_payload(0.000000, [0.000000, 0.000000, 0.000000], [0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000])
  motion_version_set(2)
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  # begin: URCap Installation Node
  #   Source: External Control, 1.0.6, FZI Research Center for Information Technology
  #   Type: External Control
  # end: URCap Installation Node
  step_count_5c381442_baa1_45d0_8eaa_99b2b35e97df = 0.0
  thread Step_Counter_Thread_3dd087c0_c26d_40b4_9cdf_c1d5737915d2():
    while (True):
      step_count_5c381442_baa1_45d0_8eaa_99b2b35e97df = step_count_5c381442_baa1_45d0_8eaa_99b2b35e97df + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_3dd087c0_c26d_40b4_9cdf_c1d5737915d2()
  $ 2 "Robot Program"
  $ 3 "Set DO[0]=On"
  set_standard_digital_out(0, True)
  $ 4 "Popup: el control sera compartido por un control externo 5 seg"
  popup("el control sera compartido por un control externo 5 seg", "Message", False, False, blocking=True)
  $ 5 "Wait: 5.0"
  sleep(5.0)
  # begin: URCap Program Node
  #   Source: External Control, 1.0.6, FZI Research Center for Information Technology
  #   Type: External Control
  $ 6 "Control by 192.168.56.1"
popup("The connection to the remote PC at 192.168.56.1:50002 could not be established. Reason: Connection refused (Connection refused)","Receive program failed", False, True, blocking=True)
sync()  # end: URCap Program Node
end
